package pl.exsio.ck.editor.view;

import java.util.HashMap;
import java.util.Map;
import pl.exsio.ck.editor.presenter.EntryEditorPresenter;

/**
 *
 * @author exsio
 */
public class EntryEditorFrame extends AbstractEntryEditorFrame {

    /**
     * Creates new form EntryEditorFrame
     */
    public EntryEditorFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        supplierLabel = new javax.swing.JLabel();
        supplyDateLabel = new javax.swing.JLabel();
        buyInvoiceNoLabel = new javax.swing.JLabel();
        recipientLabel = new javax.swing.JLabel();
        sellDateLabel = new javax.swing.JLabel();
        sellInvoiceNoLabel = new javax.swing.JLabel();
        supplierField = new javax.swing.JTextField();
        buyInvoiceNoField = new javax.swing.JTextField();
        recipientField = new javax.swing.JTextField();
        sellInvoiceNoField = new javax.swing.JTextField();
        supplyDateChooser = new com.toedter.calendar.JDateChooser();
        selLDateChooser = new com.toedter.calendar.JDateChooser();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Wprowadzanie danych");

        supplierLabel.setText("Dostawca:");

        supplyDateLabel.setText("Data dostawy: ");

        buyInvoiceNoLabel.setText("Nr faktury zakupu: ");

        recipientLabel.setText("Odbiorca: ");

        sellDateLabel.setText("Data sprzedaży: ");

        sellInvoiceNoLabel.setText("Nr faktury sprzedaży: ");

        supplyDateChooser.setDate(new java.util.Date());

        selLDateChooser.setDate(new java.util.Date());

        saveButton.setText("Zapisz");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Anuluj");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(supplierLabel)
                            .addComponent(supplyDateLabel)
                            .addComponent(buyInvoiceNoLabel)
                            .addComponent(recipientLabel)
                            .addComponent(sellDateLabel)
                            .addComponent(sellInvoiceNoLabel))
                        .addGap(18, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sellInvoiceNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(supplierField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
                                .addComponent(buyInvoiceNoField)
                                .addComponent(recipientField)
                                .addComponent(supplyDateChooser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(selLDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supplierLabel)
                    .addComponent(supplierField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(supplyDateLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(supplyDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buyInvoiceNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buyInvoiceNoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recipientField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recipientLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(selLDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sellDateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sellInvoiceNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sellInvoiceNoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.presenter.cancel();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        this.presenter.save();
    }//GEN-LAST:event_saveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buyInvoiceNoField;
    private javax.swing.JLabel buyInvoiceNoLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField recipientField;
    private javax.swing.JLabel recipientLabel;
    private javax.swing.JButton saveButton;
    private com.toedter.calendar.JDateChooser selLDateChooser;
    private javax.swing.JLabel sellDateLabel;
    private javax.swing.JTextField sellInvoiceNoField;
    private javax.swing.JLabel sellInvoiceNoLabel;
    private javax.swing.JTextField supplierField;
    private javax.swing.JLabel supplierLabel;
    private com.toedter.calendar.JDateChooser supplyDateChooser;
    private javax.swing.JLabel supplyDateLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public Map<String, Object> getValues() {
        Map<String, Object> values = new HashMap<>();
        values.put(EntryEditorPresenter.V_BUY_INVOICE_NO, this.buyInvoiceNoField.getText());
        values.put(EntryEditorPresenter.V_RECIPIENT, this.recipientField.getText());
        values.put(EntryEditorPresenter.V_SELL_DATE, this.selLDateChooser.getDate());
        values.put(EntryEditorPresenter.V_SELL_INVOICE_NO, this.sellInvoiceNoField.getText());
        values.put(EntryEditorPresenter.V_SUPPLIER, this.supplierField.getText());
        values.put(EntryEditorPresenter.V_SUPPLY_DATE, this.supplyDateChooser.getDate());
        return values;
    }
}
